### ISSUE TITLE
Usage as a X11 server

### ISSUE THREAD

**Issue by skyne98** [notgull/breadx#25]
Hey there! I am not very experienced with X11, so take everything I ask with a grain of salt, but I still have a question 😄 Can `breadx` be used to create a new desktop environment? Or, to narrow the scope, a window manager.

Thanks for your time and efforts!

**Comment by notgull** [comment]
Hello!

You could implement a window manager through this program. In fact, the i3 window manager is implemented in terms of XCB, which this library attempts to be on parity with.

However, while you *could* create a desktop environment with BreadX and BreadX only, it would be very difficult. Desktop environments like GNOME and KDE use complete graphics toolkits like GTK+ and Qt, respectively. This is because they provide drawing capabilities and built-in widget support. In contrast, breadx exists on a much lower level. Even if you did build a DE with this crate (which would be like digging a hole with a plastic spoon instead of a shovel), the current main issue in my opinion is the fact that GL acceleration is not presently supported (although I plan to add it in the future).

**Comment by skyne98** [comment]
Thanks for such a quick reply 😃 

Being completely honest, my current efforts are pretty slow and hobby-based only, so I think there is enough time to go around in my case! Also, I actually thought about using Flutter as a UI framework for the desktop environment, which in my mind simplifies things quite a lot. However, I still need to implement some kind of window manager to composite and render the windows, window handles and control elements. Do you think it's a good idea?

**Comment by notgull** [comment]
Probably not the best idea, but I won’t stop you. If you don’t have any further questions about breadx or issues with breadx, I’ll close this issue.
