### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by AdaShoelace** [notgull/breadx#38]
I would very much appreciate a roadmap or a couple of clearly stated goals/features to work on.
I really want to help take breadx towards 1.0 but don't really know where to help out.

**Comment by notgull** [comment]
Thank you for your interest in my little passion project. As I’ve been working on other projects I haven’t really had time to put polish on this one. Here’s a general list of things to do and questions to answer before I’m comfortable putting a "1.0" on this one.

* There’s still a substantial amount of the X11 API that's still only accessible via the `auto`module; mostly the extensions. I don’t think we need to have actual Display functions for *all* of the extensions. I’d be more than happy to slap a 1.0 on this once the more popular extensions are ready (xfixes, xproto, xrender, randr, xkb) as well as the ones we need for GLX (glx, dri*).
* Speaking of extensions, the `Display` object does not yet support `bigreq`. This would probably involve modifying the current request-output machinery.
* There’s a lot of unnecessary cloning that goes on behind the scenes, primarily due to the fact that requests in the `auto` module use `Vec<T>` and `String`, rather than `Cow<'a, [T]>` and `Cow<'a, str>`. This would involve modifying `breadx_generator` to keep track of lifetimes and to then use those lifetimes to parameterize the `Cow`s. I could probably whip this up in a week or so.
* Add `must_use` to XID types in order to make sure end users drop them.
* Make sure all the items in this crate are documented, and also finish the tutorial series. Will probably come after the API is finalized.
* In async mode, what happens when the future is dropped while the `Display` is reading data? The current answer is "crash and burn, poison the connection", but there’s probably a more elegant answer.
* Should `Display` be a trait? I had an idea to create an alternative connection wrapper where the fields are stored in `RefCell` or `Cell`, and that trait would be implemented on `&'a CellDisplay` (and maybe one that uses atomics and lock-free collections to be `Sync`).
* Generally just looking through the code ads and fixing bugs and making sure we're X11-compliant.

I'll definitely start cracking on this list over the course of the next week, and anyone else (including you) are welcome to take a crack at it.

**Comment by AdaShoelace** [comment]
Thanks for breaking this down!
If I have the time in the near future I would love to take a look at the unnecessary cloning.

**Comment by notgull** [comment]
Just took care of about half of the items on the list. Will probably take care of the extension stuff and the documentation later this week. @AdaShoelace, what's your progress on #39?

**Comment by AdaShoelace** [comment]
Unfortunately I haven't been able to look into it due to work and private reasons. 
I am however still interested in doing it if it's not time sensitive?

**Comment by notgull** [comment]
It’s not time sensitive, I just wanted to check in on your progress :-). Thanks again for looking into it!
