### ISSUE TITLE
Unnecessary cloning

### ISSUE THREAD

**Issue by AdaShoelace** [notgull/breadx#39]
`There’s a lot of unnecessary cloning that goes on behind the scenes, primarily due to the fact that requests in the auto module use Vec<T> and String, rather than Cow<'a, [T]> and Cow<'a, str>. This would involve modifying breadx_generator to keep track of lifetimes and to then use those lifetimes to parameterize the Cows.`

The paragraph above is taken from #38.

Not having worked with code generation all that much previously I would like to dive into this issue.
I do how ever think that I need some guidance and a little explanation regarding the code generation itself.

I mostly need an entry point to start working from. Which level in the generator would be the one to let track lifetimes to achieve the above?

**Comment by notgull** [comment]
The best place to start is probably in the `lvl3` directory, since that's where it goes from "collection" to "array or vector". You'd probably start with [this file](https://github.com/notgull/breadx/blob/master/generator/src/lvl3/ty.rs) and make the "Vector" variants lifetime aware, and then modify the 'to_syn_type" method to output a Cow instead of a Vec.

Will probably have to mess with [this file](https://github.com/notgull/breadx/blob/master/generator/src/lvl3/field.rs), too. Also change "String" to "Cow<str>".

The easy way to implement lifetimes would be to just have a thread-local variable that increments by one each time it's accessed, and then use the value to set the lifetime value in `syn`. There's probably a handful of stuff with `syn` that you'd probably have to configure as well. Consider looking at [syn's docs](https://docs.rs/syn).

**Comment by AdaShoelace** [comment]
Thanks a lot for the guidance. I'll take a closer look as soon as possible!

**Comment by AdaShoelace** [comment]
I've started to look at the problem and from what I can gather most things in the generator that holds the type `Box<str>` could be changed to a `Cow<'a, str>`. However this introduces a ton of explicit lifetimes throughout the entire module. This is of course possible to implement but I just want to check in to see whether this is okay with you and aligns with the style you're going for within the project.

**Comment by AdaShoelace** [comment]
I'm sorry but I think this is a little over my head. Perhaps should I let you handle this issue and take something easier myself?

**Comment by notgull** [comment]
It's alright, I'll try taking care of it. If you still want to help, consider trying to implement that parts of the X API I haven't yet. Here's some reference material on the X protocol:

- https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html
- https://www.x.org/releases/X11R7.7/doc/fixesproto/fixesproto.txt
- https://www.x.org/releases/current/doc/renderproto/renderproto.txt
- https://www.x.org/releases/X11R7.5/doc/randrproto/randrproto.txt
- https://www.x.org/docs/XKB/XKBproto.pdf
